---
title: "Analysis"
author: "Chloe Chah"
date: "12/2/2020"
output: html_document
---


```{r setup, include = FALSE}
library(tidyverse)
library(patchwork)
library(ggplot2)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis", 
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
knitr::opts_chunk$set(
  fig.width = 6, 
  fig.asp = .6, 
  out.width = "90%"
)
```

### What are the top 10 leading causes of death in NYC?
```{r plot 1}

nyc_df %>%
  group_by(leading_cause) %>%
  count() %>%
  arrange(desc(n)) %>%
  head(10) %>%
  ggplot(aes(x = leading_cause, y = n, fill = leading_cause))+
  geom_col()+
  labs(title = "Top 10 leading causes of death in NYC", 
    x = "Cause of death", 
    y = "Number of deaths"
  )+
  theme(legend.position = "none")+
  coord_flip() 

```

### How have the top 3 leading causes of death changed for each race in NYC?

```{r plot 2}

nyc_df %>%
  filter(leading_cause %in% c("Malignant Neoplasms", "All Other Causes", "Diseases of Heart")) %>%
  mutate(deaths = as.numeric(deaths)) %>%
  group_by(year, leading_cause, race_ethnicity) %>%  
  summarize(total_death = sum(deaths)) %>%
  ggplot(aes(x= year, y = total_death, color = leading_cause)) + 
  geom_line(size=1) + 
  labs(title='Top 3 leading causes of death by ethnicity (2007-2014)', x='Year', y='Death count') +
  facet_wrap(~race_ethnicity, ncol=3, scales = 'free_y')

```

### Are there gender differences in the leading causes of death in NYC?

```{r}

nyc_df %>%
  filter(leading_cause %in% c("Accidents Except Drug Posioning",
                              "Diabetes Mellitus", 
                              "Human Immunodeficiency Virus Disease", 
                              "Cerebrovascular Disease")) %>% 
  group_by(leading_cause, sex) %>% 
  count() %>%
  ggplot(aes(x = sex, y = n, fill = sex)) +
  geom_col() +
  labs(title='Gender differences in leading causes of death', x='Sex', y= 'Death count') +
  facet_wrap(~leading_cause)

```

