---
title: "clean_us"
author: "Amanda Tsai, Chloe Chah"
date: "11/30/2020"
output: html_document
---
This file cleans the dataset "Leading Causes of Death, US" that can be found here: https://data.cdc.gov/NCHS/NCHS-Leading-Causes-of-Death-United-States/bi63-dtpu

```{r library, message = FALSE}
library(tidyverse)
library(stringr)
```

```{r data, message = FALSE}
causes_us = 
  read_csv(file = "./data/NCHS_-_Leading_Causes_of_Death__United_States.csv", col_types = "ffffid") %>%
  janitor::clean_names() 

```

```{r separate_dfs}

# top 10 leading causes of death for the whole US every year from 1999 to 2017
us_df = causes_us %>% 
        filter(state == "United States")

# remove parentheses from cause name column

us_df$x113_cause_name = 
  gsub("\\s*\\([^\\)]+\\)","",as.character(us_df$x113_cause_name))

write_csv(us_df, "./data/Leading_Causes_of_Death_US_Only.csv")

# deaths and adjusted death rate in each state by the top 10 leading causes of death for the whole US every year (1999-2017) 
# e.g. kidney disease is a leading cause of death for the US in 2017. In NY, NJ, TX etc , there were XXX deaths by kidney disease (kidney disease doesn't have to be the leading cause in NY, NJ or TX)

state_df = causes_us %>% filter(state != "United States")

# remove parentheses from cause name column

state_df$x113_cause_name = 
  gsub("\\s*\\([^\\)]+\\)","",as.character(state_df$x113_cause_name))

write_csv(state_df, "./data/Leading_Causes_of_Death_States_Only.csv")


```


```{r nyc_data, message = FALSE}

#load dataset
nyc_df = 
  read_csv(file = "./data/New_York_City_Leading_Causes_of_Death.csv") %>%
  janitor::clean_names() 

write_csv(nyc_df, "./data/New_York_City_Leading_Causes_of_Death.csv")

# remove parentheses from leading cause column

nyc_df$leading_cause = 
  gsub("\\s*\\([^\\)]+\\)","",as.character(nyc_df$leading_cause))

```

