---
title: "Project Proposal"
output: github_document
---

### The group members (names and UNIs)
*   Chloe Chah (yc3727)
*   Mehr Shafiq (ms5965)
*   Amanda Tsai (at3535)
*   Krishna Vemulapalli (slv2129)

### The tentative project title
The Impact of COVID-19 on Consumer Activity in the US (2019-2020) 

### The motivation for this project 


### The intended final products 

Summary level tables and dashboard that visualize the comparison of commercial activity (foot traffic trends) in 2020 to the same time period in 2019 and aggregating the data by industries, specific brands, or geographic regions.

### The anticipated data sources 
[Safe Graph - U.S. Consumer Activity during COVID-19 Pandemic](https://www.safegraph.com/) 


### The planned analyses / visualizations / coding challenges

### The planned timeline

Nov 7: Submit project proposal & Request for free access to the data on SafeGraph

Nov 10-13: Project review meeting 

Nov 18 : Have dataset cleaned and ready to visualize and analyze

Nov 27 : Create a webpage and dashboard with the preliminary results and graphs

Dec 1: Troubleshoot, edit, fix, finalize all changes 

Dec 4: Record video with screencast 
